version: "3.8"

services:
  server:
    container_name: app
    build: .
    restart: always
    env_file: .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - database

  database:
    image: mysql:8.0.28
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_LOCAL_PASSWORD_DEV}
    ports:
      - '3303:${MYSQL_LOCAL_PORT_DEV}'
    volumes:
      - ./init:/docker-entrypoint-initdb.d/:ro